fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
end

platform :android do
  # Android Lanes
  
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/', flags: "-x lint")
    increment_version_code(
            gradle_file_path: "android/app/build.gradle",
            #ext_constant_name: "test"
            #app_folder_name:"app"
      )
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/', flags: "-x lint")
    end

  desc 'Ship to Playstore Alpha.'
  lane :alpha do
    build
    supply(track: 'alpha', track_promote_to: 'alpha')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
    end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
    end



end








